export const actionTypes = {
  TEXT_DATA_FETCHING: "TEXT_DATA_FETCHING",
  TEXT_DATA_FETCHED: "TEXT_DATA_FETCHED",
  TEXT_DATA_FETCH_ERROR: "TEXT_DATA_FETCH_ERROR",

  LOGO_FETCHING: "LOGO_FETCHING",
  LOGO_FETCHED: "LOGO_FETCHED",
  LOGO_FETCH_ERROR: "LOGO_FETCH_ERROR"
}