export const actionTypes = {
  FETCH_LAN_PASAA_DATA_START: "FETCH_LAN_PASAA_DATA_START",
  FETCH_LAN_PASAA_DATA_RECEIVED: "FETCH_LAN_PASAA_DATA_RECEIVED",
  FETCH_LAN_PASAA_DATA_ERROR: "FETCH_LAN_PASAA_DATA_ERROR",

  FETCH_LAN_PASAA_CATEGORIES_START: "FETCH_LAN_PASAA_CATEGORIES_START",
  FETCH_LAN_PASAA_CATEGORIES_RECEIVED: "FETCH_LAN_PASAA_CATEGORIES_RECEIVED",
  FETCH_LAN_PASAA_CATEGORIES_ERROR: "FETCH_LAN_PASAA_CATEGORIES_ERROR",

  FETCH_LAN_PASAA_PRODUCTS_START: "FETCH_LAN_PASAA_PRODUCTS_START",
  FETCH_LAN_PASAA_PRODUCTS_RECEIVED: "FETCH_LAN_PASAA_PRODUCTS_RECEIVED",
  FETCH_LAN_PASAA_PRODUCTS_ERROR: "FETCH_LAN_PASAA_PRODUCTS_ERROR",


  CATEGORY_NAV: "CATEGORY_NAV",
  ITEM_DETAILS: "ITEM_DETAILS",
  ITEM_DETAILS_CLEAR: "ITEM_DETAILS_CLEAR",

  ADD_TO_CART: "ADD_TO_CART",
  ADD_QTY: "ADD_QTY",
  MINUS_QTY: "MINUS_QTY",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  VIEW_CART: "VIEW_CART",

  ADD_ANIMATION_TO_TITLE: "ADD_ANIMATION_TO_TITLE"

}