export const actionTypes = {
  FETCH_LAN_PASAA_DATA_START: "FETCH_LAN_PASAA_DATA_START",
  FETCH_LAN_PASAA_DATA_RECEIVED: "FETCH_LAN_PASAA_DATA_RECEIVED",
  FETCH_LAN_PASAA_DATA_ERROR: "FETCH_LAN_PASAA_DATA_ERROR",

  CATEGORY_NAV: "CATEGORY_NAV",
  ITEM_DETAILS: "ITEM_DETAILS",
  ITEM_DETAILS_CLEAR: "ITEM_DETAILS_CLEAR",

  ADD_TO_CART: "ADD_TO_CART",
  DELETE_FROM_CART: "DELETE_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  VIEW_CART: "VIEW_CART",

  ADD_ANIMATION_TO_TITLE: "ADD_ANIMATION_TO_TITLE"

}