export const actionTypes = {

  API_FETCHING: 'API_FETCHING',
  API_FETCHED: 'API_FETCHED',
  API_ERROR: 'API_ERROR',

  API_DAYONETOTAL_FETCHING: 'API_DAYONETOTAL_FETCHING',
  API_DAYONETOTAL_FETCHED: 'API_DAYONETOTAL_FETCHED',
  API_DAYONETOTAL_ERROR: 'API_DAYONETOTAL_ERROR',

}