export const actionTypes = {

  SELECT_PROJECT_GROUP_ITEM: 'SELECT_PROJECT_GROUP_ITEM',
  SELECT_COLOUR_MODE: 'SELECT_COLOUR_MODE',

  PLAY_THE_TRACK: 'PLAY_THE_TRACK',
  PAUSE_THE_TRACK: 'PAUSE_THE_TRACK',
  STOP_THE_TRACK: 'STOP_THE_TRACK'


}