export const actionTypes = {

  DATA_FETCHING: "DATA_FETCHING",
  DATA_FETCHED: "DATA_FETCHED",
  DATA_ERROR: "DATA_ERROR",

  DUMMY_DATA_START: "DUMMY_DATA_START",
  DUMMY_DATA_FETCHED: "DUMMY_DATA_FETCHED",
  DUMMY_DATA_ERROR: "DUMMY_DATA_ERROR",

  SEARCH_START: "SEARCH_START",
  SEARCHING: "SEARCHING",
  SEARCH_FETCHED: "SEARCH_FETCHED",
  SEARCH_ERROR: "SEARCH_ERROR",
  SEARCH_RECIPE: "SEARCH_RECIPE",

  VIEW_RECIPE: "VIEW_RECIPE",
  FETCHING_RECIPE: "FETCHING_RECIPE",
  FETCHED_RECIPE: "FETCHED_RECIPE",
  FETCHING_RECIPE_ERROR: "FETCHING_RECIPE_ERROR",

  RECIPE_DETAIL: "RECIPE_DETAIL",
  RECIPE_INGREDIENTS: "RECIPE_INGREDIENTS",
  RECIPE_DETAIL_CLEAR: "RECIPE_DETAIL_CLEAR"

}