export const actionTypes = {
  FETCH_CATEGORY_START: "FETCH_CATEGORY_START",
  FETCH_CATEGORY_RECEIVED: "FETCH_CATEGORY_RECEIVED",
  FETCH_CATEGORY_ERROR: "FETCH_CATEGORY_ERROR",

  CATEGORY_INDEX_OF_PRODUCTS: "CATEGORY_INDEX_OF_PRODUCTS",

  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",

  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  FETCH_PRODUCTS_RECEIVED: "FETCH_PRODUCTS_RECEIVED",
  FETCH_PRODUCTS_ERROR: "FETCH_PRODUCT_ERROR",

  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  FETCH_PRODUCT_RECEIVED: "FETCH_PRODUCT_RECEIVED",
  FETCH_PRODUCT_ERROR: "FETCH_PRODUCT_ERROR"

}